# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0002_auto_20170109_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
