# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpaca', '0003_activity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='state',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
